#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/mame
#    username: root
#    password: 1234
#  sql:
#    init:
#      mode: never
#  jpa:
#    defer-datasource-initialization: true
#    #   database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
#        jdbc:
#          time_zone: UTC

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mame
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
